---
- name: Remove Wireshark from web, nfs, and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: Verify Wireshark is installed before removing (CentOS/RHEL)
      yum:
        name: wireshark
        state: present
      register: wireshark_installed
      when: ansible_facts['pkg_mgr'] == "yum"
      ignore_errors: yes

    - name: Delete Wireshark on RHEL/CentOS servers
      yum:
        name: wireshark
        state: removed
      when:
        - ansible_facts['pkg_mgr'] == "yum"
        - wireshark_installed is defined and wireshark_installed is succeeded

- name: Remove Wireshark from LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Delete Wireshark on Ubuntu/Debian servers
      apt:
        name: wireshark
        state: absent
        purge: yes
      when: ansible_facts['pkg_mgr'] == "apt"
