# MySQL configuration for the development environment
mysql_root_username: "root"
mysql_root_password: "YourNewPassword"

# Define databases and users to be created for the dev environment
mysql_databases:
  - name: homestead
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: homestead
    host: "%"
    password: YourNewPassword
    priv: "*.*:ALL,GRANT"