    pipeline {
    agent any

  stages {
     stage("Initial cleanup") {
      steps {
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }

    stage('Checkout SCM') {
      steps {
        git branch: 'main', credentialsId: 'gashity_token', url: 'https://github.com/Prince-Tee/ansible-config-mgt.git'
      }
    }
    
    stage('Prepare Ansible For Execution') {
      steps {
        sh 'echo ${WORKSPACE}'
        sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
      }
    }

   stage('Test SSH Connection') {
    steps {
        sshagent(['Taiwo']) {
            sh 'ssh -o StrictHostKeyChecking=no ubuntu@172.31.47.62 exit'
        }
    }
}
    
   


    stage('Run Ansible playbook') {
      steps {
       ansiblePlaybook credentialsId: 'Taiwo', disableHostKeyChecking: true, installation: 'ansible-config-mgt', inventory: 'inventory/uat.ini', playbook: 'playbooks/uat-webservers.yml', vaultTmpPath: ''
      }
    }
      stage('Clean Workspace after build') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }


    }
}

