---
- name: update web, nfs, and db servers
  hosts: webservers, nfs, db
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version on RHEL/CentOS servers
      yum:
        name: wireshark
        state: latest
      when: ansible_facts['pkg_mgr'] == "yum"

- name: update LB server
  hosts: lb
  become: yes
  tasks:
    - name: Update apt repository
      apt: 
        update_cache: yes
      when: ansible_facts['pkg_mgr'] == "apt"

    - name: ensure wireshark is at the latest version on Ubuntu/Debian servers
      apt:
        name: wireshark
        state: latest
      when: ansible_facts['pkg_mgr'] == "apt"
